name: Run Captain Shell Script

on:
  workflow_dispatch:
    inputs:
      k3s_versions:
        description: 'Provide the list of k3s versions (comma separated)'
        required: true
        default: 'v1.34.0-rc1+k3s1,v1.33.4-rc1+k3s1,v1.32.8-rc1+k3s1,v1.31.12-rc1+k3s1'
      rke2_versions:
        description: 'Provide the list of rke2 versions (comma separated)'
        required: true
        default: 'v1.34.0-rc1+rke2r1,v1.33.4-rc1+rke2r1,v1.32.8-rc1+rke2r1,v1.31.12-rc1+rke2r1,v1.30.14-rc1+rke2r3'
      page_size:
        description: 'Page size for API queries'
        required: false
        default: '150'

jobs:
  run-script-job:
    runs-on: ubuntu-latest # Specifies the operating system for the runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Action to check out the repository content
      
      - name: Update and install dependencies
        run: sudo apt-get update && sudo apt-get install -y jq curl skopeo # Installs necessary packages

      - name: Make script executable (if needed)
        run: chmod +x .scripts/captain.sh # Grants execute permission to the script

      - name: Run the shell script
        run: .scripts/captain.sh -v "${{ github.event.inputs.versions }}"  -d -p "${{ github.event.inputs.page_size }}"# Executes the shell script