name: Run Captain Shell Script

on:
  workflow_dispatch:
    inputs:
      k3s_versions:
        description: 'Provide the list of k3s versions (comma separated)'
        required: false
        default: 'v1.34.0-rc1+k3s1,v1.33.4-rc1+k3s1,v1.32.8-rc1+k3s1,v1.31.12-rc1+k3s1'
      rke2_versions:
        description: 'Provide the list of rke2 versions (comma separated)'
        required: false
        default: 'v1.34.0-rc1+rke2r1,v1.33.4-rc1+rke2r1,v1.32.8-rc1+rke2r1,v1.31.12-rc1+rke2r1'
      rke2_lts_versions:
        description: 'Provide the list of rke2 lts versions to test prime registry (comma separated)'
        required: false
        default: 'v1.30.14-rc1+rke2r3'
      page_size:
        description: 'Page size for API queries'
        required: false
        default: '150'

jobs:
  run-script-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Update and install necessary packages
        run: sudo apt-get update && sudo apt-get install -y jq curl skopeo

      - name: Change permissions and make script executable (if needed)
        working-directory: ./scripts
        run: chmod +x ./captain.sh

      - name: Verify K3S versions - run captain shell script
        working-directory: ./scripts
        if: ${{ github.event.inputs.k3s_versions != '' }}
        run: ./captain.sh -v "${{ github.event.inputs.k3s_versions }}"  -d -p "${{ github.event.inputs.page_size }}"
        shell: sh
        continue-on-error: true

      - name: Verify RKE2 versions - run captain shell script
        working-directory: ./scripts
        if: ${{ github.event.inputs.rke2_versions != '' }}
        run: ./captain.sh -v "${{ github.event.inputs.rke2_versions }}"  -d -p "${{ github.event.inputs.page_size }}"
        shell: sh
        continue-on-error: true

      - name: Verify LTS RKE2 versions - run captain shell script
        working-directory: ./scripts
        if: ${{ github.event.inputs.rke2_lts_versions != '' }}
        run: ./captain.sh -l "${{ github.event.inputs.rke2_lts_versions }}"  -d
        shell: sh
